(class main
        (method void main ()
(begin (try
(call me bar)
             (print "The thrown exception was: " exception)
            )
            (print "This should fail: " exception)  # fails with NAME_ERROR
          )
) )